### ISSUE TITLE
Refactor schemas to remove explicit id attributes, fix Department definition insertion

### ISSUE THREAD

**Issue by zillwa** [Last-Men-Standing/blueview-database#1]
We want Postgres to create the id's for the table.

**Comment by cengelj** [comment]
Do you think a surrogate key would be a good way of accomplishing this?

**Comment by cengelj** [comment]
It seems that if we were to use a surrogate key it would actually avoid needing to change all that much, we could just remove the other two IDs from the table, and instead we'd just need to add a line at the bottom of the department table. What are thoughts on doing it this way?
